Revert PR #2
mathur/mathur.github.io pull request #3
Opened 2024-12-30 21:20 UTC by krishmas

This reverts commit d17d53e2ccdf6f9aa7d5b180eb47481fbbd30068, reversing changes made to 1e78fe2c3b5fccaad7dcbbe527921ef23eed84b2.

Text changes are inferior to the original copy. Making this now before conflict resolution overhead increases

2024-12-30 21:23 UTC, pywoo2 commented on index.html
> +                I am also a past <a href="https://hackny.org/fellows-program">hackNY fellow</a>.
not sure about this one

2024-12-30 21:24 UTC, pywoo2 commented on index.html
> +                worked on Onboard Systems software at <a href="https://www.nuro.ai">Nuro</a>, and before that,
breaking change.

2024-12-30 21:24 UTC, pywoo2 commented on index.html
> +                    class="fa fa-twitter" aria-hidden="true"></i> <a href="https://www.x.com/ro_mathur">Twitter</a>-
blocked ong frfr no cap

2024-12-30 21:24 UTC, pywoo2 requested changes
BLOCKED

2024-12-30 21:25 UTC, krishmas commented
> BLOCKED

discussed offline, seems we're good to go on this one

2024-12-30 21:25 UTC, pywoo2 commented
@@@@@@@@@
~~~~~~~~~~~~~~


DO NOT MERGE THIS!!!!

~~~~~~~~~~~~~~
@@@@@@@@@

2024-12-30 21:29 UTC, pywoo2 requested changes
This PR is exactly what is wrong with this community. Ever since @krishmas joined us here, things have been downhill.

@mathur if you care at ALL about this project that we've built together, don't let things like this in.

2025-01-02 22:21 UTC, mathur commented
Sorry for the delay in addressing this pull request. I agree with core teammate @pywoo2 , this PR serves to do nothing except confuse users. We cannot accept random contributions from the community like this. Closing.

2025-01-02 22:21 UTC, closed without merging